"""get rid of tg_ in schema description (we have prefix for that)

Revision ID: 09a8065b33e6
Revises: 83e5db294b72
Create Date: 2024-04-01 11:40:26.343404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a8065b33e6'
down_revision = '83e5db294b72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tg_message_deletion_chat_id_fkey', 'tg_message_deletion', type_='foreignkey')
    op.drop_constraint('tg_message_deletion_user_id_fkey', 'tg_message_deletion', type_='foreignkey')
    op.create_foreign_key(None, 'tg_message_deletion', 'tg_chat', ['chat_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'tg_message_deletion', 'tg_user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tg_message_deletion', type_='foreignkey')
    op.drop_constraint(None, 'tg_message_deletion', type_='foreignkey')
    op.create_foreign_key('tg_message_deletion_user_id_fkey', 'tg_message_deletion', 'tg_user', ['user_id'], ['id'])
    op.create_foreign_key('tg_message_deletion_chat_id_fkey', 'tg_message_deletion', 'tg_chat', ['chat_id'], ['id'])
    # ### end Alembic commands ###
