"""Add Raw User field to the User to store all user object we are getting from Telegram

Revision ID: 0daf9f90e92a
Revises: 4353fe9d9d92
Create Date: 2025-02-11 14:36:43.760470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0daf9f90e92a'
down_revision = '4353fe9d9d92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('user_raw', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_user', 'user_raw')
    # ### end Alembic commands ###
