"""Try to restore vector column

Revision ID: 0f15d2e4ada6
Revises: f15c99de6298
Create Date: 2024-11-11 20:11:18.015019

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '0f15d2e4ada6'
down_revision = 'f15c99de6298'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_message_log', sa.Column('embedding', Vector, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_message_log', 'embedding')
    # ### end Alembic commands ###
