"""add field to store messages we are going to delete

Revision ID: 1892948cfa3a
Revises: fa5c4b259375
Create Date: 2024-02-22 15:50:52.014679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1892948cfa3a'
down_revision = 'fa5c4b259375'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_message_deletion',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'active'::character varying"), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('message_posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['tg_chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tg_user.id'], ),
    sa.PrimaryKeyConstraint('id', name='message_deletion_pkey')
    )
    op.create_index(op.f('ix_tg_message_deletion_chat_id'), 'tg_message_deletion', ['chat_id'], unique=False)
    op.create_index(op.f('ix_tg_message_deletion_message_id'), 'tg_message_deletion', ['message_id'], unique=False)
    op.create_index(op.f('ix_tg_message_deletion_user_id'), 'tg_message_deletion', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_message_deletion_user_id'), table_name='tg_message_deletion')
    op.drop_index(op.f('ix_tg_message_deletion_message_id'), table_name='tg_message_deletion')
    op.drop_index(op.f('ix_tg_message_deletion_chat_id'), table_name='tg_message_deletion')
    op.drop_table('tg_message_deletion')
    # ### end Alembic commands ###
