"""Let's add used_for_training parameter to message_log to know which messages we already used for training

Revision ID: 1d43efb99d7b
Revises: 9084bf4a8a82
Create Date: 2024-05-01 10:19:43.796352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d43efb99d7b'
down_revision = '9084bf4a8a82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_message_log', sa.Column('used_for_training', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_message_log', 'used_for_training')
    # ### end Alembic commands ###
