"""add manually verified field to message_log to not verify again and again the same messages

Revision ID: 218c392d95db
Revises: 9abf3ffe06b5
Create Date: 2024-05-21 10:32:56.049085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218c392d95db'
down_revision = '9abf3ffe06b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_message_log', sa.Column('manually_verified', sa.Boolean(), nullable=False, server_default=sa.sql.expression.False_()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_message_log', 'manually_verified')
    # ### end Alembic commands ###
