"""add scheduled_messages to DB

Revision ID: 25acea2d794e
Revises: 374d4c6d1de6
Create Date: 2024-03-18 20:41:33.208713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25acea2d794e'
down_revision = '374d4c6d1de6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_scheduled_message',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('frequency_seconds', sa.Integer(), nullable=False),
    sa.Column('last_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_of_the_day', sa.Time(), nullable=True),
    sa.Column('day_of_the_week', sa.Integer(), nullable=True),
    sa.Column('day_of_the_month', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['tg_chat.id'], ),
    sa.PrimaryKeyConstraint('id', name='scheduled_message_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_scheduled_message')
    # ### end Alembic commands ###
