"""Let's store not only spam, but all messages and only mark spam ones

Revision ID: 2b6d173b7958
Revises: ad57360a6d04
Create Date: 2024-04-30 19:11:15.100915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6d173b7958'
down_revision = 'ad57360a6d04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_message_log', sa.Column('message_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_tg_message_log_message_id'), 'tg_message_log', ['message_id'], unique=False)
    op.create_unique_constraint('uix_message_id_chat_id', 'tg_message_log', ['message_id', 'chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_message_id_chat_id', 'tg_message_log', type_='unique')
    op.drop_index(op.f('ix_tg_message_log_message_id'), table_name='tg_message_log')
    op.drop_column('tg_message_log', 'message_id')
    # ### end Alembic commands ###
