"""add user global ban

Revision ID: 2f7ad4297a5c
Revises: e8e7eb251b91
Create Date: 2023-07-14 14:29:15.078465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7ad4297a5c'
down_revision = 'e8e7eb251b91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_user_global_ban',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tg_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_global_ban_pkey')
    )
    op.create_index(op.f('ix_tg_user_global_ban_user_id'), 'tg_user_global_ban', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_user_global_ban_user_id'), table_name='tg_user_global_ban')
    op.drop_table('tg_user_global_ban')
    # ### end Alembic commands ###
