"""add auto_reply structure to DB

Revision ID: 374d4c6d1de6
Revises: 0d8a00111299
Create Date: 2024-03-17 21:03:51.629715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374d4c6d1de6'
down_revision = '0d8a00111299'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_auto_reply',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('reply', sa.Text(), nullable=False),
    sa.Column('last_reply_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_delay', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['tg_chat.id'], ),
    sa.PrimaryKeyConstraint('id', name='auto_reply_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_auto_reply')
    # ### end Alembic commands ###
