"""add reply_to_message_id to db

Revision ID: 3812728d217b
Revises: 47634157f97d
Create Date: 2024-08-26 23:12:08.182700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3812728d217b'
down_revision = '47634157f97d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_message_log', sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_message_log', 'reply_to_message_id')
    # ### end Alembic commands ###
