"""add active boolen column to scheduled messages

Revision ID: 3c503b36b592
Revises: 25acea2d794e
Create Date: 2024-03-18 21:46:56.370099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c503b36b592'
down_revision = '25acea2d794e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add the 'active' column, allowing nulls initially
    op.add_column('tg_scheduled_message', sa.Column('active', sa.Boolean(), nullable=True))

    # Set default values for the existing rows
    op.execute('UPDATE tg_scheduled_message SET active = TRUE')  # or FALSE, depending on your desired default

    # Alter 'active' column to non-nullable and set default value for new records
    op.alter_column('tg_scheduled_message', 'active', existing_type=sa.Boolean(), nullable=False, server_default=sa.true())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_scheduled_message', 'active')
    # ### end Alembic commands ###
