"""Add Raw Message field to the Message_Log to store all object we are getting from Telegram

Revision ID: 4353fe9d9d92
Revises: 2422f509a134
Create Date: 2025-02-11 13:00:09.633172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4353fe9d9d92'
down_revision = '2422f509a134'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_message_log', sa.Column('raw_message', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_message_log', 'raw_message')
    # ### end Alembic commands ###
