"""separate rating and support grouping chats

Revision ID: 47614ab74c72
Revises: 0a0551281943
Create Date: 2023-08-16 21:23:13.386574

"""
from sqlalchemy import text
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47614ab74c72'
down_revision = '0a0551281943'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_chat_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='chat_group_pkey')
    )
    op.create_table('tg_user_rating',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('judge_id', sa.BigInteger(), nullable=False),
    sa.Column('change_value', sa.Integer(), nullable=False),
    sa.Column('change_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['tg_chat.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['judge_id'], ['tg_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tg_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_rating_pkey')
    )
    op.create_index(op.f('ix_tg_user_rating_chat_id'), 'tg_user_rating', ['chat_id'], unique=False)
    op.create_index(op.f('ix_tg_user_rating_judge_id'), 'tg_user_rating', ['judge_id'], unique=False)
    op.create_index(op.f('ix_tg_user_rating_user_id'), 'tg_user_rating', ['user_id'], unique=False)
    op.add_column('tg_chat', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tg_chat', 'tg_chat_group', ['group_id'], ['id'])
    # ### end Alembic commands ###

    # Migrate rating data from tg_user_status to tg_user_rating
    conn = op.get_bind()

    query = text("""
            INSERT INTO tg_user_rating(user_id, chat_id, judge_id, change_value, change_date)
            SELECT user_id, chat_id, 88834504 AS judge_id, rating, created_at AS change_date
            FROM tg_user_status
            WHERE rating IS NOT NULL AND rating != 0;
        """)

    conn.execute(query)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tg_chat', type_='foreignkey')
    op.drop_column('tg_chat', 'group_id')
    op.drop_index(op.f('ix_tg_user_rating_user_id'), table_name='tg_user_rating')
    op.drop_index(op.f('ix_tg_user_rating_judge_id'), table_name='tg_user_rating')
    op.drop_index(op.f('ix_tg_user_rating_chat_id'), table_name='tg_user_rating')
    op.drop_table('tg_user_rating')
    op.drop_table('tg_chat_group')
    # ### end Alembic commands ###
