"""Add forwarded message details to Message_Log

Revision ID: 47634157f97d
Revises: e2a941f65d6a
Create Date: 2024-08-26 21:55:57.495841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47634157f97d'
down_revision = 'e2a941f65d6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_message_log', sa.Column('forwarded_message_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_message_log', 'forwarded_message_content')
    # ### end Alembic commands ###
