"""Let's add created_at to users

Revision ID: 5d8dec652190
Revises: 1d43efb99d7b
Create Date: 2024-05-01 20:46:51.995565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8dec652190'
down_revision = '1d43efb99d7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_user', 'created_at')
    # ### end Alembic commands ###
