"""make embedding nullable 

Revision ID: 5df78f037c3e
Revises: 7940dc8d9a70
Create Date: 2025-05-27 18:47:20.621645

"""
from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df78f037c3e'
down_revision = '7940dc8d9a70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_embeddings_auto_reply_trigger', 'embedding',
               existing_type=Vector,
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_embeddings_auto_reply_trigger', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(),
               nullable=False)
    # ### end Alembic commands ###
