"""add report_power to the report (if user have additional power)

Revision ID: 68890a2eabb3
Revises: d35b10ca86ee
Create Date: 2024-02-14 14:08:10.225519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68890a2eabb3'
down_revision = 'd35b10ca86ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the report_power column with a temporary nullable setting to accommodate existing rows.
    op.add_column('tg_report', sa.Column('report_power', sa.Integer(), nullable=True))

    # Set a default value for existing rows. Adjust the default as necessary for your application logic.
    op.execute('UPDATE tg_report SET report_power = 1')

    # Change the column to be NOT NULL now that all existing rows have a value.
    op.alter_column('tg_report', 'report_power', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_report', 'report_power')
    # ### end Alembic commands ###
