"""add usage_count to Auto_Reply to count ussage

Revision ID: 6b3d0f112e83
Revises: 3c503b36b592
Create Date: 2024-03-19 13:25:35.532767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3d0f112e83'
down_revision = '3c503b36b592'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_auto_reply', sa.Column('usage_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_auto_reply', 'usage_count')
    # ### end Alembic commands ###
