"""prepare for embeddings autoreply

Revision ID: 7940dc8d9a70
Revises: 8755d201572c
Create Date: 2025-05-27 16:09:26.182710

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '7940dc8d9a70'
down_revision = '8755d201572c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_embeddings_auto_reply_content',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('reply', sa.Text(), nullable=False),
    sa.Column('last_reply_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_delay', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='embeddings_auto_reply_content_pkey')
    )
    op.create_table('tg_embeddings_auto_reply_trigger',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger_text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['tg_chat.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['tg_embeddings_auto_reply_content.id'], ),
    sa.PrimaryKeyConstraint('id', name='embeddings_auto_reply_trigger_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_embeddings_auto_reply_trigger')
    op.drop_table('tg_embeddings_auto_reply_content')
    # ### end Alembic commands ###
