"""let's store only boolen is_forwarded because bot does not get forwarded id for some reason (may be not have access to another chat where it is forwarded from)

Revision ID: 811c555eafdf
Revises: 3812728d217b
Create Date: 2024-08-27 01:50:05.350880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811c555eafdf'
down_revision = '3812728d217b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_message_log', sa.Column('is_forwarded', sa.Boolean(), nullable=True))
    op.drop_column('tg_message_log', 'forwarded_chat_id')
    op.drop_column('tg_message_log', 'forwarded_message_id')
    op.drop_column('tg_message_log', 'forwarded_message_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_message_log', sa.Column('forwarded_message_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tg_message_log', sa.Column('forwarded_message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('tg_message_log', sa.Column('forwarded_chat_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('tg_message_log', 'is_forwarded')
    # ### end Alembic commands ###
