"""add spamreportlog

Revision ID: 83e5db294b72
Revises: 6b3d0f112e83
Create Date: 2024-04-01 11:35:53.367222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e5db294b72'
down_revision = '6b3d0f112e83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_spamreportlog',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_nickname', sa.Text(), nullable=True),
    sa.Column('user_current_rating', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_nickname', sa.Text(), nullable=True),
    sa.Column('reason_for_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['tg_user.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['tg_chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tg_user.id'], ),
    sa.PrimaryKeyConstraint('id', name='spam_report_log_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_spamreportlog')
    # ### end Alembic commands ###
