"""add active flag to chat

Revision ID: 8755d201572c
Revises: 0daf9f90e92a
Create Date: 2025-05-20 17:11:29.704529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8755d201572c'
down_revision = '0daf9f90e92a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_chat', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_chat', 'active')
    # ### end Alembic commands ###
