"""add_group_id_support_to_trigger_action_chain

Revision ID: 8b083406d2f8
Revises: 005e75a3ddde
Create Date: 2025-11-08 21:39:47.705487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b083406d2f8'
down_revision = '005e75a3ddde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tg_message_log_user_id_created_at', table_name='tg_message_log')
    op.drop_index('ix_tg_report_chatid_userid_reason', table_name='tg_report')
    op.add_column('tg_trigger_action_chain', sa.Column('group_id', sa.Integer(), nullable=True))
    op.alter_column('tg_trigger_action_chain', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_tg_trigger_action_chain_group_id'), 'tg_trigger_action_chain', ['group_id'], unique=False)
    op.create_index('ix_trigger_action_chain_group_id_enabled', 'tg_trigger_action_chain', ['group_id', 'enabled'], unique=False)
    op.create_foreign_key(None, 'tg_trigger_action_chain', 'tg_chat_group', ['group_id'], ['id'])
    # Add check constraint to ensure exactly one of chat_id or group_id is set
    op.create_check_constraint(
        'trigger_action_chain_chat_or_group_check',
        'tg_trigger_action_chain',
        '(chat_id IS NOT NULL AND group_id IS NULL) OR (chat_id IS NULL AND group_id IS NOT NULL)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop check constraint
    op.drop_constraint('trigger_action_chain_chat_or_group_check', 'tg_trigger_action_chain', type_='check')
    op.drop_constraint(None, 'tg_trigger_action_chain', type_='foreignkey')
    op.drop_index('ix_trigger_action_chain_group_id_enabled', table_name='tg_trigger_action_chain')
    op.drop_index(op.f('ix_tg_trigger_action_chain_group_id'), table_name='tg_trigger_action_chain')
    op.alter_column('tg_trigger_action_chain', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('tg_trigger_action_chain', 'group_id')
    op.create_index('ix_tg_report_chatid_userid_reason', 'tg_report', ['chat_id', 'reported_user_id'], unique=False)
    op.create_index('idx_tg_message_log_user_id_created_at', 'tg_message_log', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
