"""add enabled/disabled flags for triggers

Revision ID: 99f88cbbaaef
Revises: 5df78f037c3e
Create Date: 2025-05-27 18:59:39.149099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f88cbbaaef'
down_revision = '5df78f037c3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_auto_reply', sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('tg_embeddings_auto_reply_trigger', sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_embeddings_auto_reply_trigger', 'enabled')
    op.drop_column('tg_auto_reply', 'enabled')
    # ### end Alembic commands ###
