"""make user_id in user_global_ban unique

Revision ID: b27cde79a360
Revises: 2f7ad4297a5c
Create Date: 2023-07-14 20:33:19.859674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27cde79a360'
down_revision = '2f7ad4297a5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tg_user_global_ban_user_id', table_name='tg_user_global_ban')
    op.create_index(op.f('ix_tg_user_global_ban_user_id'), 'tg_user_global_ban', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_user_global_ban_user_id'), table_name='tg_user_global_ban')
    op.create_index('ix_tg_user_global_ban_user_id', 'tg_user_global_ban', ['user_id'], unique=False)
    # ### end Alembic commands ###
