"""let's add field when we are going to delete message automatically even without trigger (we will write fron for it later

Revision ID: cd3c4aef762f
Revises: 1892948cfa3a
Create Date: 2024-02-22 15:54:48.427998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3c4aef762f'
down_revision = '1892948cfa3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_message_deletion', sa.Column('scheduled_deletion_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_message_deletion', 'scheduled_deletion_time')
    # ### end Alembic commands ###
