"""add reason to warn/report db

Revision ID: d35b10ca86ee
Revises: 552ecebe931f
Create Date: 2023-09-10 15:21:11.564436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35b10ca86ee'
down_revision = '552ecebe931f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_report', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_report', 'reason')
    # ### end Alembic commands ###
