"""Add forwarded_message_id and forwarded_chat_id to Message_Log

Revision ID: e2a941f65d6a
Revises: 218c392d95db
Create Date: 2024-08-26 21:31:07.801778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a941f65d6a'
down_revision = '218c392d95db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_message_log', sa.Column('forwarded_message_id', sa.BigInteger(), nullable=True))
    op.add_column('tg_message_log', sa.Column('forwarded_chat_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_message_log', 'forwarded_chat_id')
    op.drop_column('tg_message_log', 'forwarded_message_id')
    # ### end Alembic commands ###
