"""Add reporting to db

Revision ID: e8e7eb251b91
Revises: e5454b165995
Create Date: 2023-04-16 20:43:19.252818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8e7eb251b91'
down_revision = 'e5454b165995'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_report',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('reported_user_id', sa.BigInteger(), nullable=False),
    sa.Column('reporting_user_id', sa.BigInteger(), nullable=False),
    sa.Column('reported_message_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='report_pkey')
    )
    op.create_index(op.f('ix_tg_report_chat_id'), 'tg_report', ['chat_id'], unique=False)
    op.create_index(op.f('ix_tg_report_reported_message_id'), 'tg_report', ['reported_message_id'], unique=False)
    op.create_index(op.f('ix_tg_report_reported_user_id'), 'tg_report', ['reported_user_id'], unique=False)
    op.create_index(op.f('ix_tg_report_reporting_user_id'), 'tg_report', ['reporting_user_id'], unique=False)
    op.drop_table('tg_reaction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_reaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('msg_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('emoticon', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tg_reaction_pkey')
    )
    op.drop_index(op.f('ix_tg_report_reporting_user_id'), table_name='tg_report')
    op.drop_index(op.f('ix_tg_report_reported_user_id'), table_name='tg_report')
    op.drop_index(op.f('ix_tg_report_reported_message_id'), table_name='tg_report')
    op.drop_index(op.f('ix_tg_report_chat_id'), table_name='tg_report')
    op.drop_table('tg_report')
    # ### end Alembic commands ###
