"""Add trigger action chain tables with json config

Revision ID: f5d5db155a1a
Revises: 5b25c90fc5fb
Create Date: 2025-10-20 18:36:32.686428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d5db155a1a'
down_revision = '5b25c90fc5fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_trigger_action_chain',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['tg_chat.id'], ),
    sa.PrimaryKeyConstraint('id', name='trigger_action_chain_pkey')
    )
    op.create_index(op.f('ix_tg_trigger_action_chain_chat_id'), 'tg_trigger_action_chain', ['chat_id'], unique=False)
    op.create_index('ix_trigger_action_chain_chat_id_enabled', 'tg_trigger_action_chain', ['chat_id', 'enabled'], unique=False)
    op.create_table('tg_chain_action',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['tg_trigger_action_chain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chain_action_pkey')
    )
    op.create_index('ix_chain_action_chain_id', 'tg_chain_action', ['chain_id'], unique=False)
    op.create_table('tg_chain_execution_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('trigger_results', sa.JSON(), nullable=True),
    sa.Column('actions_executed', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['tg_trigger_action_chain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chain_execution_log_pkey')
    )
    op.create_index('ix_chain_execution_log_chain_id', 'tg_chain_execution_log', ['chain_id'], unique=False)
    op.create_index('ix_chain_execution_log_chat_id', 'tg_chain_execution_log', ['chat_id'], unique=False)
    op.create_table('tg_chain_trigger',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['tg_trigger_action_chain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chain_trigger_pkey')
    )
    op.create_index('ix_chain_trigger_chain_id', 'tg_chain_trigger', ['chain_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chain_trigger_chain_id', table_name='tg_chain_trigger')
    op.drop_table('tg_chain_trigger')
    op.drop_index('ix_chain_execution_log_chat_id', table_name='tg_chain_execution_log')
    op.drop_index('ix_chain_execution_log_chain_id', table_name='tg_chain_execution_log')
    op.drop_table('tg_chain_execution_log')
    op.drop_index('ix_chain_action_chain_id', table_name='tg_chain_action')
    op.drop_table('tg_chain_action')
    op.drop_index('ix_trigger_action_chain_chat_id_enabled', table_name='tg_trigger_action_chain')
    op.drop_index(op.f('ix_tg_trigger_action_chain_chat_id'), table_name='tg_trigger_action_chain')
    op.drop_table('tg_trigger_action_chain')
    # ### end Alembic commands ###
