"""add field to regularity check if bot have admin permissions

Revision ID: fa5c4b259375
Revises: 68890a2eabb3
Create Date: 2024-02-14 16:47:31.854187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5c4b259375'
down_revision = '68890a2eabb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_chat', sa.Column('last_admin_permission_check', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_chat', 'last_admin_permission_check')
    # ### end Alembic commands ###
